# Generated by Django 3.0.8 on 2020-07-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='TRYBLOG', max_length=255),
        ),
    ]
